# KSM tuning - applied at boot
w /sys/kernel/mm/ksm/pages_to_scan - - - - 100000
w /sys/kernel/mm/ksm/sleep_millisecs - - - - 500
w /sys/kernel/mm/ksm/smart_scan - - - - 1
w /sys/kernel/mm/ksm/use_zero_pages - - - - 1